name: Android APK Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      # Ensure only valid JVM args are passed to Gradle. Do NOT put Gradle CLI flags here.
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      JAVA_TOOL_OPTIONS: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Set up Flutter 3.32.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Show tool versions
        run: |
          java -version
          flutter --version

      - name: Prepare Gradle wrapper
        run: |
          chmod +x android/gradlew

      - name: Clear conflicting env vars (safety)
        run: |
          echo "JAVA_TOOL_OPTIONS=" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.daemon=false" >> $GITHUB_ENV

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK (release)
        run: flutter build apk --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error


