name: Build Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'android/**'
      - 'ios/**'
      - 'windows/**'

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Check Flutter version
        run: |
          flutter --version
          flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Check for dependency conflicts
        run: flutter pub deps

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --set-exit-if-changed .

  test-build-android:
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Test Android build
        run: flutter build apk --debug --verbose

  test-build-windows:
    runs-on: windows-latest
    needs: check-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Test Windows build
        run: flutter build windows --debug --verbose

  test-build-ios:
    runs-on: macos-latest
    needs: check-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Test iOS build
        run: flutter build ios --debug --no-codesign --verbose
        continue-on-error: true

  build-summary:
    runs-on: ubuntu-latest
    needs: [test-build-android, test-build-windows, test-build-ios]
    if: always()
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Platform | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test-build-android.result }}" == "success" ]; then
            echo "| Android | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Android | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-build-windows.result }}" == "success" ]; then
            echo "| Windows | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Windows | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-build-ios.result }}" == "success" ]; then
            echo "| iOS | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| iOS | ⚠️ Failed (Expected without signing) |" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Flutter Version**: 3.32.5" >> $GITHUB_STEP_SUMMARY
          echo "**Build Time**: $(date)" >> $GITHUB_STEP_SUMMARY
