name: 构建并发布跨平台应用

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发构建
  workflow_dispatch:  # 允许手动触发
    inputs:
      version:
        description: '发布版本号 (例如: v1.0.0)'
        required: true
        default: 'v1.0.0'

# 设置工作流权限
permissions:
  contents: write  # 需要写权限来创建Release
  actions: read    # 需要读权限来访问构建产物

env:
  FLUTTER_VERSION: '3.35.0'

jobs:
  # 准备发布
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    # 注意：我们不在这里创建Release，而是在所有构建完成后创建
    - name: 设置版本变量
      id: version
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref_name }}" == v* ]]; then
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          VERSION="v$(date +'%Y.%m.%d')-build.$(date +'%H%M')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        fi
        echo "BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

  # 构建Android APK
  build-android:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      # 确保不会把 Gradle CLI 选项当成 JVM 选项传给 Java
      JAVA_TOOL_OPTIONS: ""
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true  # 启用Flutter缓存

    - name: 设置JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: 安装 Android SDK 组件
      uses: android-actions/setup-android@v3
      with:
        packages: platform-tools platforms;android-35 build-tools;35.0.0

    - name: 清理可能冲突的环境变量
      run: |
        # 防止 CI 或上游 action 注入导致 JVM 误读的参数
        echo "JAVA_TOOL_OPTIONS=" >> $GITHUB_ENV
        echo "GRADLE_OPTS=-Dorg.gradle.daemon=false" >> $GITHUB_ENV

    # 缓存Gradle依赖
    - name: 缓存Gradle依赖
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 缓存Flutter依赖
    - name: 缓存Flutter依赖
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: 设置Gradle环境
      run: |
        mkdir -p ~/.gradle
        # 使用更保守的JVM配置，避免与项目配置冲突
        echo "org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+UseG1GC" > ~/.gradle/gradle.properties
        echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties

        # 验证Java版本
        java -version
        echo "JAVA_HOME=$JAVA_HOME"

    - name: 诊断构建环境
      run: |
        echo "🔍 诊断构建环境..."
        
        # 检查Java环境
        echo "=== Java环境 ==="
        java -version
        javac -version
        echo "JAVA_HOME: $JAVA_HOME"
        
        # 检查系统资源
        echo "=== 系统资源 ==="
        free -h || echo "无法获取内存信息"
        df -h || echo "无法获取磁盘信息"
        nproc || echo "无法获取CPU核心数"
        
        # 检查Gradle配置
        echo "=== Gradle配置 ==="
        cat ~/.gradle/gradle.properties || echo "未找到全局gradle.properties"
        cat android/gradle.properties || echo "未找到项目gradle.properties"
        
        # 检查Flutter环境
        echo "=== Flutter环境 ==="
        flutter doctor -v
        flutter --version

    - name: 安装Flutter依赖
      run: |
        # 只在缓存未命中时清理
        if [ ! -d ".dart_tool" ]; then
          flutter clean
        fi
        flutter pub get

    - name: 生成代码
      run: dart run build_runner build --delete-conflicting-outputs

    # 初始化Gradle Wrapper并预热守护进程
    - name: 初始化Gradle Wrapper并预热守护进程
      run: |
        echo "🔍 检查当前目录结构..."
        ls -la

        echo "🔍 检查android目录..."
        ls -la android/

        cd android

        # 确保gradlew文件存在并有执行权限
        if [ ! -f "gradlew" ]; then
          echo "❌ gradlew文件不存在，尝试重新生成..."

          # 尝试使用gradle wrapper命令重新生成
          if command -v gradle >/dev/null 2>&1; then
            echo "📦 使用gradle命令重新生成wrapper..."
            gradle wrapper --gradle-version 8.10.2
          else
            echo "❌ gradle命令不可用，手动创建gradlew..."
            # 从GitHub下载标准的gradlew文件（与 Gradle 8.10.2 匹配）
            curl -L -o gradlew "https://raw.githubusercontent.com/gradle/gradle/v8.10.2/gradlew"
            curl -L -o gradlew.bat "https://raw.githubusercontent.com/gradle/gradle/v8.10.2/gradlew.bat"
          fi
        fi

        # 确保gradlew有执行权限
        chmod +x gradlew
        chmod +x gradlew.bat 2>/dev/null || true

        # 确保gradle-wrapper.jar存在
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "📦 下载 gradle-wrapper.jar..."
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar \
            "https://github.com/gradle/gradle/raw/v8.10.2/gradle/wrapper/gradle-wrapper.jar"
        fi

        # 运行初始化脚本（如果存在）
        if [ -f "init-gradle-wrapper.sh" ]; then
          echo "🔧 运行 Gradle Wrapper 初始化脚本..."
          chmod +x init-gradle-wrapper.sh
          ./init-gradle-wrapper.sh
        fi

        # 验证gradlew可执行
        echo "🔍 验证gradlew文件..."
        ls -la gradlew
        file gradlew

        # 预热 Gradle 守护进程
        echo "🔥 预热 Gradle 守护进程..."
        echo "✅ gradlew 执行权限已设置"
        echo "🧪 测试 gradlew..."
        
        # 显示Java版本
        java -version
        
        echo "✅ Gradle Wrapper 初始化成功"
        
        # 验证gradlew文件
        echo "🔍 验证gradlew文件..."
        ls -la gradlew
        file gradlew
        
        # 预热 Gradle 守护进程
        echo "🔥 预热 Gradle 守护进程..."
        java -version
        
        # 测试基本的 gradle 命令，不使用 tasks
        echo "🔧 测试 Gradle 配置..."
        ./gradlew --version || {
          echo "⚠️ gradlew --version 失败，尝试修复..."
          
          # 重新下载 gradle-wrapper.jar（8.10.2）
          echo "📦 重新下载 gradle-wrapper.jar..."
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar \
            "https://github.com/gradle/gradle/raw/v8.10.2/gradle/wrapper/gradle-wrapper.jar"
          
          # 再次尝试
          ./gradlew --version
        }
        
        # 如果 --version 成功，再尝试 tasks 命令
        echo "🔧 验证 Gradle 任务..."
        ./gradlew help --quiet || {
          echo "⚠️ help 命令失败，跳过任务验证..."
        }

    - name: 构建Android APK
      timeout-minutes: 30
      env:
        JAVA_OPTS: "-Xmx2G"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      run: |
        echo "🚀 开始构建Android APK..."
        echo "📊 构建开始时间: $(date)"
        
        # 显示环境信息
        echo "🔍 环境信息:"
        echo "JAVA_HOME=$JAVA_HOME"
        echo "JAVA_OPTS=$JAVA_OPTS"
        echo "GRADLE_OPTS=$GRADLE_OPTS"
        java -version
        echo "Flutter 版本:"
        flutter --version
        
        # 显示系统资源信息
        echo "🔍 系统资源信息:"
        free -h || echo "无法获取内存信息"
        df -h || echo "无法获取磁盘信息"
        
        # 显示 Gradle 配置
        echo "🔍 Gradle 配置:"
        cat ~/.gradle/gradle.properties || echo "未找到全局 gradle.properties"
        cat android/gradle.properties || echo "未找到项目 gradle.properties"
        
        # 清理之前的构建
        echo "🧹 清理之前的构建..."
        flutter clean
        
        # 重新获取依赖
        echo "📦 重新获取依赖..."
        flutter pub get

        # 使用优化的构建参数
        echo "🔨 开始构建..."
        flutter build apk --release --dart-define=flutter.inspector.structuredErrors=false --target-platform android-arm64,android-arm

        echo "✅ Android APK构建完成"
        echo "📊 构建结束时间: $(date)"

        # 显示构建产物信息
        echo "📦 构建产物:"
        ls -la build/app/outputs/flutter-apk/

    - name: 打包Android构建产物
      run: |
        mkdir -p android-build

        # 检查是否有分架构APK文件
        if [ -f "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" ]; then
          echo "📱 找到分架构APK文件，开始打包..."

          # 复制所有架构的APK文件
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk android-build/AnywhereChat-Android-${{ needs.prepare.outputs.version }}-arm64.apk

          # 如果有其他架构的APK也复制
          if [ -f "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk" ]; then
            cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk android-build/AnywhereChat-Android-${{ needs.prepare.outputs.version }}-arm32.apk
          fi

        elif [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
          echo "📱 找到通用APK文件..."
          cp build/app/outputs/flutter-apk/app-release.apk android-build/AnywhereChat-Android-${{ needs.prepare.outputs.version }}.apk
        else
          echo "❌ 未找到APK文件"
          exit 1
        fi

        # 显示最终的构建产物
        echo "📦 最终构建产物:"
        ls -la android-build/

    - name: 上传Android构建产物
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: |
          android-build/*.apk



  # 构建iOS应用
  build-ios:
    needs: prepare
    runs-on: macos-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'

    - name: 清理并安装Flutter依赖
      run: |
        flutter clean
        rm -rf .dart_tool
        flutter pub get --no-precompile

    - name: 生成代码
      run: dart run build_runner build --delete-conflicting-outputs

    - name: 设置iOS构建环境
      run: |
        # 尝试选择一个可用的iOS SDK版本
        if xcrun --sdk iphoneos --show-sdk-version 2>/dev/null | grep -q "17"; then
          echo "使用 iOS 17 SDK"
          export IOS_SDK_VERSION="17.0"
        elif xcrun --sdk iphoneos --show-sdk-version 2>/dev/null | grep -q "16"; then
          echo "使用 iOS 16 SDK" 
          export IOS_SDK_VERSION="16.0"
        else
          echo "使用默认 iOS SDK"
          export IOS_SDK_VERSION="15.0"
        fi
        
        echo "IOS_SDK_VERSION=$IOS_SDK_VERSION" >> $GITHUB_ENV
        
        # 显示Xcode和iOS SDK信息
        xcrun --sdk iphoneos --show-sdk-version || echo "无法获取iOS SDK版本"
        xcodebuild -showsdks | grep -i ios || echo "无法列出iOS SDK"

    - name: 构建iOS应用（无签名）
      run: |
        # 检查可用的iOS SDK并使用合适的版本
        echo "🔍 检查可用的iOS SDK版本..."
        xcodebuild -showsdks | grep -i ios
        
        # 获取可用的iOS SDK版本
        AVAILABLE_IOS_SDK=$(xcodebuild -showsdks | grep 'iphoneos' | tail -1 | sed 's/.*iphoneos//' | xargs)
        echo "📱 使用iOS SDK版本: $AVAILABLE_IOS_SDK"
        
        # 构建iOS应用，指定SDK版本
        echo "📱 开始构建iOS应用..."
        flutter build ios --release --no-codesign \
          --dart-define=flutter.inspector.structuredErrors=false
      continue-on-error: true

    - name: 创建IPA文件
      run: |
        mkdir -p ios-build
        mkdir -p Payload

        # 检查构建产物是否存在
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          echo "✅ 找到iOS构建产物，开始创建IPA..."

          # 复制.app到Payload目录（IPA标准结构）
          cp -r build/ios/iphoneos/Runner.app Payload/

          # 创建IPA文件（IPA本质上是一个特殊的ZIP文件）
          zip -r AnywhereChat-iOS-${{ needs.prepare.outputs.version }}-unsigned.ipa Payload

          # 移动IPA到构建目录
          mv AnywhereChat-iOS-${{ needs.prepare.outputs.version }}-unsigned.ipa ios-build/

          # 仅保留 IPA

          # 显示打包内容
          echo "📦 打包内容:"
          ls -la ios-build/

          # 显示IPA文件信息
          echo "📱 IPA文件信息:"
          file ios-build/*.ipa

          echo "✅ iOS IPA文件创建完成"
        else
          echo "❌ 未找到iOS构建产物，创建错误信息..."

          # 创建错误信息
          echo "iOS构建失败" > ios-build/build-error.txt
          echo "版本: ${{ needs.prepare.outputs.version }}" >> ios-build/build-error.txt
          echo "错误: 未找到构建产物 build/ios/iphoneos/Runner.app" >> ios-build/build-error.txt
          echo "构建时间: $(date)" >> ios-build/build-error.txt

          # 显示构建目录内容用于调试
          echo "🔍 构建目录内容:"
          find build -name "*.app" -type d 2>/dev/null || echo "未找到.app文件"
        fi

    - name: 上传iOS构建产物
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios-build/*.ipa

  # 注意：Windows构建已被移除，因为持续出现文件锁定问题




  # 完成发布
  finalize-release:
    needs: [prepare, build-android, build-ios]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: 下载所有构建产物
      uses: actions/download-artifact@v4

    - name: 获取当前时间
      id: current-time
      run: echo "time=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

    - name: 创建Release并上传所有文件
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.prepare.outputs.version }}
        name: Campus Copilot ${{ needs.prepare.outputs.version }}
        body: |
          # Campus Copilot ${{ needs.prepare.outputs.version }}

          **发布时间**: ${{ steps.current-time.outputs.time }}

          ## 📦 构建产物

          ### 移动端
          - ✅ **Android APK**: 适用于Android 5.0+设备，可直接安装
          - ✅ **iOS IPA**: 未签名IPA文件，需要使用第三方工具或Xcode签名后安装

          ### 桌面端
          - ❌ **Windows**: 暂时移除

          ## 🔧 技术信息

          - **Flutter版本**: ${{ env.FLUTTER_VERSION }}
          - **Dart版本**: 3.8.1
          - **构建环境**: GitHub Actions
          - **许可证**: 双重许可证 (Apache 2.0 / 商业许可证)

          ## 📞 支持

          - 商业许可证咨询: 927751260@qq.com
          - 技术支持: GitHub Issues
        files: |
          android-build/*.apk
          ios-build/*.ipa
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 构建完成通知
      run: |
        echo "🎉 AnywhereChat 跨平台构建完成!"
        echo "📱 Android: ✅"
        echo "🍎 iOS: ✅"
        echo "🖥️ Windows: ✅"
        echo "🔗 Release链接: https://github.com/${{ github.repository }}/releases/tag/${{ needs.prepare.outputs.version }}"